{% set name = "fossil" %}
{% set version = "2.14" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.fossil-scm.org/xfer/uv/{{ name }}-src-{{ version }}.tar.gz
  sha256: b8d0c920196dd8ae29152fa7448e513a1fa7c588871b785e3fbfc07b42a05fb9

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - ccache  # [unix]
    - cmake  # [win]
    - make  # [unix]
    - perl  # [win]
  host:
    - openssl
    - sqlite >=3.34.0  # [unix]
    - tk
    - zlib
  run:
    - openssl
    - sqlite >=3.34.0  # [unix]
    - tk
    - zlib

test:
  commands:
    - fossil --help

about:
  home: https://fossil-scm.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYRIGHT-BSD2.txt
  summary: >
    Fossil is a simple, high-reliability, distributed software configuration management system with these advanced features:

  doc_url: https://fossil-scm.org/index.html/doc/trunk/www/permutedindex.html
  dev_url: https://fossil-scm.org/index.html/dir?ci=tip

extra:
  recipe-maintainers:
    - bollwyvl
