{% set name = "fossil" %}
{% set version = "2.8" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.fossil-scm.org/xfer/uv/{{ name }}-src-{{ version }}.tar.gz
  sha256: 6a32bec73de26ff5cc8bbb0b7b45360f4e4145931fd215ed91414ed190b3715d

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - ccache  # [unix]
    - cmake  # [win]
    - make  # [unix]
    - perl  # [win]
  host:
    - openssl
    - sqlite
    - tk
    - zlib
  run:
    - openssl
    - sqlite
    - tk
    - zlib

test:
  commands:
    - fossil --help

about:
  home: https://fossil-scm.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYRIGHT-BSD2.txt
  summary: >
    Fossil is a simple, high-reliability, distributed software configuration
    management system with these advanced features:

  doc_url: https://fossil-scm.org/index.html/doc/trunk/www/permutedindex.html
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - bollwyvl
