{% set name = "fossil" %}
{% set version = "2.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.fossil-scm.org/xfer/uv/{{ name }}-src-{{ version }}.tar.gz
  sha256: 8de5367c462d0671b0ca579d909ab1e25efaaf294f37ce9af93f04b965694166

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - ccache  # [unix]
    - cmake  # [win]
    - make  # [unix]
    - perl  # [win]
  host:
    - openssl
    - sqlite >=3.33.0 # [unix]
    - tk
    - zlib
  run:
    - openssl
    - sqlite >=3.33.0 # [unix]
    - tk
    - zlib

test:
  commands:
    - fossil --help

about:
  home: https://fossil-scm.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYRIGHT-BSD2.txt
  summary: >
    Fossil is a simple, high-reliability, distributed software configuration management system with these advanced features:

  doc_url: https://fossil-scm.org/index.html/doc/trunk/www/permutedindex.html
  dev_url: https://fossil-scm.org/index.html/dir?ci=tip

extra:
  recipe-maintainers:
    - bollwyvl
