travis:
  secure:
    BINSTAR_TOKEN: QrctDxE6OJTSxnE3oxqmQZweVFJddL+q7oCkIf7Ipt8320rObH9YHCNe7b81bHqwGUw60Mtn4R45KQ0aVMHM9c8GpoYYYSAILDzq2GZT+770vQq9Gw2G5WdoTebTrEXh7HWiYR06rPkLBRYLM3ntTGuf0398df5R1715hn12qk2bEZGxqhOyhb8M/XyYBcE3dl3gXiHg15AsKSaSsF/piYJTijqccJdORoIFsOZWNiQvAw5b2N9hNJNdqUvxF7ax0QUSfQiePOT7ta/utBESU+obSPTRW2vbT5NMyed4Ici6t6yMavggz+bdGvyeJG/9JSPzlj08L1tAsNbj7vAv2xN74raX6tTmIIRQfsq6u+GBD35OVN4QFwULm/MEJZ7r21Ej6DWSr2q7OwtMM2InP+eICkK9FQvDByYgHpWxcV9JjeJQEDF/qBPbsGkI2+nklgxWI47yW79qFe24jY3XYNeX5eADRFY+iN3oC5F/gKbOSvtqKzPLUwUraLTzKp/jnJGiqG0U15a/iaIa7jplMJ2eiljHaPpe4avq4nycOme1Irvhy1J16kkhv77xLzlGeP/BF2h2NxrjKzG7sSt3Q6UANwFWvFqZqrSMtHB9+tHAd//tQNRThE0Ts3kfBRAfaQrNVoSFB2zc0ieG0mq/ZqcCdbWJsi3URgdoQTOmkIY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
